version: "3.8"

services:
  rstudio:
    image: sagebionetworks/rstudio:4.1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rstudio
    env_file:
      - .env
    volumes:
      - .:/home/rstudio/awesome-project:rw
    ports:
      - "${HOST_PORT}:8787"
    command: rstudio
